export const mockData = [
  {
    name: "Alice Johnson",
    userName: "Alice Johnson",
    userType: "Admin",
    website: "https://alicejohnson.com",
    workspaceId: "WID001",
    language: "english",
  },
  {
    name: "Bob Smith",
    userName: "Bob Smith",
    userType: "User",
    website: "https://bobsmith.net",
    workspaceId: "WID002",
    language: "tamil",
  },
  {
    name: "Carol White",
    userName: "Carol White",
    userType: "User",
    website: "https://carolwhite.org",
    workspaceId: "WID003",
    language: "French",
  },
  {
    name: "David Brown",
    userName: "David Brown",
    userType: "Guest",
    website: "https://davidbrown.io",
    workspaceId: "WID004",
    language: "German",
  },
  {
    name: "Eve Black",
    userName: "Eve Black",
    userType: "Admin",
    website: "https://eveblack.biz",
    workspaceId: "WID005",
    language: "Chinese",
  },
  {
    name: "Frank Green",
    userName: "Frank Green",
    userType: "User",
    website: "https://frankgreen.info",
    workspaceId: "WID006",
    language: "Japanese",
  },
  {
    name: "Grace Lewis",
    userName: "Grace Lewis",
    userType: "Guest",
    website: "https://gracelewis.co",
    workspaceId: "WID007",
    language: "Korean",
  },
  {
    name: "Hank Adams",
    userName: "Hank Adams",
    userType: "Admin",
    website: "https://hankadams.com",
    workspaceId: "WID008",
    language: "Russian",
  },
  {
    name: "Ivy Walker",
    userName: "Ivy Walker",
    userType: "User",
    website: "https://ivywalker.net",
    workspaceId: "WID009",
    language: "Italian",
  },
  {
    name: "Jack Scott",
    userName: "Jack Scott",
    userType: "Guest",
    website: "https://jackscott.org",
    workspaceId: "WID010",
    language: "Portuguese",
  },
];

export const mockUser = [
  {
    username: "john_doe",
    name: "John Doe",
    email: "john.doe@example.com",
    contactNumber: "123-456-7890",
  },
  {
    username: "jane_smith",
    name: "Jane Smith",
    email: "jane.smith@example.com",
    contactNumber: "234-567-8901",
  },
  {
    username: "bob_jones",
    name: "Bob Jones",
    email: "bob.jones@example.com",
    contactNumber: "345-678-9012",
  },
  {
    username: "alice_johnson",
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    contactNumber: "456-789-0123",
  },
  {
    username: "charlie_brown",
    name: "Charlie Brown",
    email: "charlie.brown@example.com",
    contactNumber: "567-890-1234",
  },
  {
    username: "david_lee",
    name: "David Lee",
    email: "david.lee@example.com",
    contactNumber: "678-901-2345",
  },
  {
    username: "emily_clark",
    name: "Emily Clark",
    email: "emily.clark@example.com",
    contactNumber: "789-012-3456",
  },
  {
    username: "frank_harris",
    name: "Frank Harris",
    email: "frank.harris@example.com",
    contactNumber: "890-123-4567",
  },
  {
    username: "grace_miller",
    name: "Grace Miller",
    email: "grace.miller@example.com",
    contactNumber: "901-234-5678",
  },
  {
    username: "harry_white",
    name: "Harry White",
    email: "harry.white@example.com",
    contactNumber: "012-345-6789",
  },
  {
    username: "isabella_taylor",
    name: "Isabella Taylor",
    email: "isabella.taylor@example.com",
    contactNumber: "123-456-7891",
  },
  {
    username: "jack_moore",
    name: "Jack Moore",
    email: "jack.moore@example.com",
    contactNumber: "234-567-8902",
  },
  {
    username: "karen_anderson",
    name: "Karen Anderson",
    email: "karen.anderson@example.com",
    contactNumber: "345-678-9013",
  },
  {
    username: "larry_martin",
    name: "Larry Martin",
    email: "larry.martin@example.com",
    contactNumber: "456-789-0124",
  },
  {
    username: "maria_thompson",
    name: "Maria Thompson",
    email: "maria.thompson@example.com",
    contactNumber: "567-890-1235",
  },
  {
    username: "nathan_walker",
    name: "Nathan Walker",
    email: "nathan.walker@example.com",
    contactNumber: "678-901-2346",
  },
  {
    username: "olivia_scott",
    name: "Olivia Scott",
    email: "olivia.scott@example.com",
    contactNumber: "789-012-3457",
  },
  {
    username: "paul_hall",
    name: "Paul Hall",
    email: "paul.hall@example.com",
    contactNumber: "890-123-4568",
  },
  {
    username: "quincy_allen",
    name: "Quincy Allen",
    email: "quincy.allen@example.com",
    contactNumber: "901-234-5679",
  },
  {
    username: "rachel_lopez",
    name: "Rachel Lopez",
    email: "rachel.lopez@example.com",
    contactNumber: "012-345-6790",
  },
  {
    username: "steve_clarkson",
    name: "Steve Clarkson",
    email: "steve.clarkson@example.com",
    contactNumber: "123-456-7892",
  },
  {
    username: "tina_davis",
    name: "Tina Davis",
    email: "tina.davis@example.com",
    contactNumber: "234-567-8903",
  },
  {
    username: "victor_evans",
    name: "Victor Evans",
    email: "victor.evans@example.com",
    contactNumber: "345-678-9014",
  },
];

export const mockBooks = [
  {
    name: "To Kill a Mockingbird",
    author: "Harper Lee",
    currentAvailabilityStatus: "Available",
  },
  {
    name: "1984",
    author: "George Orwell",
    currentAvailabilityStatus: "Not Available",
  },
  {
    name: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    currentAvailabilityStatus: "Available",
  },
  {
    name: "Moby Dick",
    author: "Herman Melville",
    currentAvailabilityStatus: "Not Available",
  },
  {
    name: "Pride and Prejudice",
    author: "Jane Austen",
    currentAvailabilityStatus: "Available",
  },
  {
    name: "The Catcher in the Rye",
    author: "J.D. Salinger",
    currentAvailabilityStatus: "Not Available",
  },
  {
    name: "War and Peace",
    author: "Leo Tolstoy",
    currentAvailabilityStatus: "Available",
  },
  {
    name: "The Odyssey",
    author: "Homer",
    currentAvailabilityStatus: "Available",
  },
  {
    name: "Brave New World",
    author: "Aldous Huxley",
    currentAvailabilityStatus: "Not Available",
  },
  {
    name: "The Iliad",
    author: "Homer",
    currentAvailabilityStatus: "Not Available",
  },
  {
    name: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    currentAvailabilityStatus: "Available",
  },
  {
    name: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    currentAvailabilityStatus: "Available",
  },
  {
    name: "Anna Karenina",
    author: "Leo Tolstoy",
    currentAvailabilityStatus: "Not Available",
  },
  {
    name: "The Hobbit",
    author: "J.R.R. Tolkien",
    currentAvailabilityStatus: "Available",
  },
  {
    name: "Fahrenheit 451",
    author: "Ray Bradbury",
    currentAvailabilityStatus: "Not Available",
  },
  {
    name: "Jane Eyre",
    author: "Charlotte Brontë",
    currentAvailabilityStatus: "Available",
  },
  {
    name: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    currentAvailabilityStatus: "Not Available",
  },
  {
    name: "Wuthering Heights",
    author: "Emily Brontë",
    currentAvailabilityStatus: "Available",
  },
  {
    name: "Les Misérables",
    author: "Victor Hugo",
    currentAvailabilityStatus: "Not Available",
  },
  {
    name: "A Tale of Two Cities",
    author: "Charles Dickens",
    currentAvailabilityStatus: "Available",
  },
  {
    name: "on Quixote",
    author: "Miguel de Cervantes",
    currentAvailabilityStatus: "Not Available",
  },
  {
    name: "The Alchemist",
    author: "Paulo Coelho",
    currentAvailabilityStatus: "Available",
  },
  {
    name: "The Divine Comedy",
    author: "Dante Alighieri",
    currentAvailabilityStatus: "Not Available",
  },
];

export const mockTransactions = [
  {
    userDetails: {
      userId: 1,
      name: "Alice Johnson",
      email: "alice.johnson@example.com",
      contactNumber: "555-1234",
    },
    bookDetails: {
      bookId: 101,
      name: "To Kill a Mockingbird",
      author: "Harper Lee",
    },
    dueDate: "2024-08-15",
    transactionType: "borrowed",
  },
  {
    userDetails: {
      userId: 2,
      name: "Bob Smith",
      email: "bob.smith@example.com",
      contactNumber: "555-5678",
    },
    bookDetails: {
      bookId: 102,
      name: "1984",
      author: "George Orwell",
    },
    dueDate: "2024-08-20",
    transactionType: "borrowed",
  },
  {
    userDetails: {
      userId: 3,
      name: "Catherine Lee",
      email: "catherine.lee@example.com",
      contactNumber: "555-8765",
    },
    bookDetails: {
      bookId: 103,
      name: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
    },
    dueDate: "2024-08-10",
    transactionType: "returned",
  },
  {
    userDetails: {
      userId: 4,
      name: "David Kim",
      email: "david.kim@example.com",
      contactNumber: "555-4321",
    },
    bookDetails: {
      bookId: 104,
      name: "Moby Dick",
      author: "Herman Melville",
    },
    dueDate: "2024-08-25",
    transactionType: "borrowed",
  },
  {
    userDetails: {
      userId: 5,
      name: "Emily Davis",
      email: "emily.davis@example.com",
      contactNumber: "555-0987",
    },
    bookDetails: {
      bookId: 105,
      name: "Pride and Prejudice",
      author: "Jane Austen",
    },
    dueDate: "2024-08-18",
    transactionType: "returned",
  },
  {
    userDetails: {
      userId: 6,
      name: "Frank Harris",
      email: "frank.harris@example.com",
      contactNumber: "555-1122",
    },
    bookDetails: {
      bookId: 106,
      name: "The Catcher in the Rye",
      author: "J.D. Salinger",
    },
    dueDate: "2024-08-12",
    transactionType: "borrowed",
  },
  {
    userDetails: {
      userId: 7,
      name: "Grace Wilson",
      email: "grace.wilson@example.com",
      contactNumber: "555-3344",
    },
    bookDetails: {
      bookId: 107,
      name: "War and Peace",
      author: "Leo Tolstoy",
    },
    dueDate: "2024-08-22",
    transactionType: "returned",
  },
  {
    userDetails: {
      userId: 8,
      name: "Henry Martinez",
      email: "henry.martinez@example.com",
      contactNumber: "555-5566",
    },
    bookDetails: {
      bookId: 108,
      name: "The Odyssey",
      author: "Homer",
    },
    dueDate: "2024-08-28",
    transactionType: "borrowed",
  },
  {
    userDetails: {
      userId: 9,
      name: "Isabella Taylor",
      email: "isabella.taylor@example.com",
      contactNumber: "555-7788",
    },
    bookDetails: {
      bookId: 109,
      name: "Brave New World",
      author: "Aldous Huxley",
    },
    dueDate: "2024-08-19",
    transactionType: "returned",
  },
  {
    userDetails: {
      userId: 10,
      name: "Jack Anderson",
      email: "jack.anderson@example.com",
      contactNumber: "555-9900",
    },
    bookDetails: {
      bookId: 110,
      name: "The Iliad",
      author: "Homer",
    },
    dueDate: "2024-08-30",
    transactionType: "borrowed",
  },
];
